[project]
name = "qdrant-deep-dive"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastembed>=0.7.4",
    "ipykernel>=7.1.0",
    "python-dotenv>=1.2.1",
    "qdrant-client>=1.16.1",
]
